import json
import re
import pandas as pd
from pathlib import Path
from datetime import datetime, timezone, date
from tqdm import tqdm
import numpy as np

# ================================================================
# CONFIG
# ================================================================
html_folder = Path("html_dump")

# Columns to keep for FACTS
keep_columns_facts = [
    "source_file",
    "company_id",
    "unique_symbol",
    "share_price",
    "market_cap",
    "intrinsic_discount",
    "pe",
    "pb",
    "peg",
    "preferred_multiple",
    "preferred_multiple_reason",
    "preferred_multiple_secondary",
    "preferred_relative_multiple_average_peer_value",
    "justified_preferred_multiple_ratio",
    "roe",
    "roa",
    "eps",
    "debt_equity",
    "dividend_current",
    "dividend_future",
    "future_growth_1y",
    "future_growth_3y",
    "future_roe_1y",
    "future_roe_3y",
    "past_growth_1y",
    "past_growth_5y",
    "analyst_count",
    "insider_buying",
    "dividend_dividend_paying_years",
    "dividend_payout_ratio",
    "dividend_payout_ratio_3y",
    "dividend_dividend_yield_growth_annual",
    "dividend_first_payment",
    "dividend_last_payment",
    "dividend_buyback_yield",
    "dividend_total_shareholder_yield",
    "dividend_payout_ratio_median_3yr",
    "dividend_dividend_payments_growth_annual",
    "dividend_dividend_payments_single_growth_1y",
    "dividend_dividend_payments_single_growth_3y",
    "dividend_dividend_payments_single_growth_5y",
    "dividend_dividend_payments_ltm",
    "dividend_cash_payout_ratio",
    "dividend_dividend_currency_iso",
    "future_return_on_equity_1y",
    "future_return_on_equity_3y",
    "future_earnings_per_share_growth_1y",
    "future_earnings_per_share_growth_3y",
    "future_earnings_per_share_1y",
    "future_earnings_per_share_2y",
    "future_earnings_per_share_3y",
    "future_revenue_growth_1y",
    "future_revenue_growth_2y",
    "future_revenue_growth_3y",
    "future_revenue_1y",
    "future_revenue_2y",
    "future_revenue_3y",
    "future_cash_ops_growth_1y",
    "future_cash_ops_growth_2y",
    "future_cash_ops_growth_3y",
    "future_cash_ops_1y",
    "future_cash_ops_2y",
    "future_cash_ops_3y",
    "future_net_income_growth_1y",
    "future_net_income_growth_2y",
    "future_net_income_growth_3y",
    "future_net_income_1y",
    "future_net_income_2y",
    "future_net_income_3y",
    "future_minimum_earnings_growth",
    "future_earnings_per_share_growth_annual",
    "future_revenue_growth_annual",
    "future_cash_ops_growth_annual",
    "future_net_income_growth_annual",
    "future_ebitda_1y",
    "future_ebitda_growth_1y",
    "future_forward_pe_1y",
    "future_forward_price_to_sales_1y",
    "future_forward_ev_to_ebitda_1y",
    "future_forward_ev_to_sales_1y",
    "future_gross_profit_margin_1y",
    "future_net_income_margin_1y",
    "health_net_income",
    "health_net_interest_expense",
    "health_cash_operating",
    "health_total_assets",
    "health_ppe",
    "health_inventory",
    "health_cash_st_investments",
    "health_receivables",
    "health_current_assets",
    "health_total_equity",
    "health_total_debt",
    "health_long_term_debt",
    "health_long_term_liab",
    "health_accounts_payable",
    "health_total_current_liab",
    "health_total_liab_equity",
    "health_total_debt_equity",
    "health_total_inventory",
    "health_debt_to_equity_ratio",
    "health_debt_to_equity_ratio_past",
    "health_net_debt_to_equity",
    "health_assets_equity_ratio",
    "health_fixed_to_total_assets",
    "health_current_assets_to_total_debt",
    "health_operating_cash_flow_to_total_debt",
    "health_net_interest_cover",
    "health_current_solvency_ratio",
    "health_current_assets_to_long_term_liab",
    "health_operating_expenses",
    "health_operating_expenses_growth_annual",
    "health_operating_expenses_stable_years",
    "health_operating_expenses_growth_years",
    "health_median_2yr_net_income",
    "health_industry_analysis_net_loans",
    "health_industry_analysis_loan_losses",
    "health_industry_analysis_net_int_margin",
    "health_industry_analysis_total_deposits",
    "health_industry_analysis_allowance_loan_losses",
    "health_industry_analysis_net_loans_to_deposits",
    "health_industry_analysis_total_bank_liabilities",
    "health_industry_analysis_allowance_non_perf_loans",
    "health_industry_analysis_net_loans_to_total_assets",
    "health_industry_analysis_non_perf_loans_total_loans",
    "health_industry_analysis_deposits_to_bank_liabilities",
    "health_capex",
    "health_capex_growth_1y",
    "health_capex_growth_annual",
    "health_net_debt",
    "health_management_rate_return",
    "health_book_value_per_share",
    "health_levered_free_cash_flow",
    "health_levered_free_cash_flow_1y",
    "health_levered_free_cash_flow_2y",
    "health_levered_free_cash_flow_growth_annual",
    "health_levered_free_cash_flow_growth_years",
    "health_levered_free_cash_flow_stable_years",
    "health_cash_from_investing",
    "health_net_debt_to_ebitda",
    "health_capitalisation_percent",
    "health_capitalisation_percent_1y",
    "health_cash_operating_growth_1y",
    "health_cash_from_investing_1y",
    "health_inventory_growth_1y",
    "health_net_operating_assets",
    "health_net_operating_assets_1y",
    "health_aggregate_accruals",
    "health_accounts_receivable_growth_1y",
    "health_accounts_receivable_percent",
    "health_long_term_assets",
    "health_last_balance_sheet_update",
    "health_current_portion_lease_liabilities",
    "health_long_term_portion_lease_liabilities",
    "health_total_lease_liabilities",
    "health_restricted_cash",
    "health_restricted_cash_ratio",
    "health_levered_free_cash_flow_break_even_years",
    "health_net_operating_assets_ltm_history_0",
    "health_net_operating_assets_ltm_history_1",
    "health_net_operating_assets_ltm_history_2",
    "health_net_operating_assets_ltm_history_3",
    "health_aggregate_accruals_ltm_history_0",
    "health_aggregate_accruals_ltm_history_1",
    "health_aggregate_accruals_ltm_history_2",
    "health_aggregate_accruals_ltm_history_3",
    "health_accrual_ratio_from_cashflow_ltm_history_0",
    "health_accrual_ratio_from_cashflow_ltm_history_1",
    "health_accrual_ratio_from_cashflow_ltm_history_2",
    "health_total_assets_ltm_history_0",
    "health_total_assets_ltm_history_1",
    "health_total_assets_ltm_history_2",
    "health_total_assets_ltm_history_3",
    "health_total_assets_ltm_history_4",
    "health_total_assets_ltm_history_5",
    "health_total_current_liab_ltm_history_0",
    "health_total_current_liab_ltm_history_1",
    "health_total_current_liab_ltm_history_2",
    "health_total_current_liab_ltm_history_3",
    "health_total_current_liab_ltm_history_4",
    "health_total_current_liab_ltm_history_5",
    "management_management_tenure",
    "management_board_tenure",
    "management_management_age",
    "management_board_age",
    "management_insider_buying_ratio",
    "management_total_shares_bought",
    "management_total_shares_sold",
    "management_total_employees",
    "management_ceo_salary_growth_1y",
    "misc_is_volatile",
    "misc_analyst_count",
    "misc_shares_outstanding_single_growth_1y",
    "misc_shares_outstanding_single_growth_5y",
    "misc_daily_return_standard_deviation_90d",
    "misc_daily_return_standard_deviation_1y",
    "past_revenue",
    "past_revenue_usd",
    "past_revenue_ltm_history_0",
    "past_revenue_ltm_history_1",
    "past_revenue_ltm_history_2",
    "past_revenue_ltm_history_3",
    "past_revenue_ltm_history_4",
    "past_revenue_ltm_history_5",
    "past_revenue_ltm_history_6",
    "past_revenue_ltm_history_7",
    "past_revenue_ltm_history_8",
    "past_revenue_ltm_history_9",
    "past_revenue_ltm_history_10",
    "past_operating_revenue",
    "past_net_income",
    "past_net_income_usd",
    "past_net_income_ltm_history_0",
    "past_net_income_ltm_history_1",
    "past_net_income_ltm_history_2",
    "past_net_income_ltm_history_3",
    "past_net_income_ltm_history_4",
    "past_net_income_ltm_history_5",
    "past_net_income_ltm_history_6",
    "past_net_income_ltm_history_7",
    "past_net_income_ltm_history_8",
    "past_net_income_ltm_history_9",
    "past_net_income_ltm_history_10",
    "past_earnings_per_share",
    "past_earnings_per_share_ltm_history_0",
    "past_earnings_per_share_ltm_history_1",
    "past_earnings_per_share_ltm_history_2",
    "past_earnings_per_share_ltm_history_3",
    "past_earnings_per_share_ltm_history_4",
    "past_earnings_per_share_ltm_history_5",
    "past_earnings_per_share_ltm_history_6",
    "past_earnings_per_share_ltm_history_7",
    "past_earnings_per_share_ltm_history_8",
    "past_earnings_per_share_ltm_history_9",
    "past_earnings_per_share_ltm_history_10",
    "past_earnings_per_share_1y",
    "past_earnings_per_share_3y",
    "past_earnings_per_share_5y",
    "past_earnings_per_share_5y_avg",
    "past_ebt_excluding",
    "past_earnings_continued_ops",
    "past_total_assets",
    "past_total_equity",
    "past_current_liabilities",
    "past_return_on_equity",
    "past_return_on_assets",
    "past_return_on_capital_employed",
    "past_return_on_capital_employed_past",
    "past_return_on_capital_growth",
    "past_earnings_per_share_growth_1y",
    "past_earnings_per_share_growth_3y",
    "past_earnings_per_share_growth_5y",
    "past_net_income_1y",
    "past_net_income_2y",
    "past_net_income_3y",
    "past_net_income_4y",
    "past_net_income_5y",
    "past_net_income_5y_avg",
    "past_net_income_growth_1y",
    "past_net_income_growth_3y",
    "past_net_income_growth_5y",
    "past_revenue_growth_1y",
    "past_revenue_growth_3y",
    "past_revenue_growth_5y",
    "past_days_since_last_update",
    "past_last_earnings_update",
    "past_last_earnings_update_annual",
    "past_industry_analysis_d_a_expense",
    "past_industry_analysis_r_d_expense",
    "past_industry_analysis_non_op_expense",
    "past_industry_analysis_sales_marketing",
    "past_industry_analysis_revenue_segments_banking",
    "past_industry_analysis_stock_based_comp",
    "past_industry_analysis_general_administrative",
    "past_industry_analysis_selling_general_admin_expenses",
    "past_ebit",
    "past_ebit_ltm_history_0",
    "past_ebit_ltm_history_1",
    "past_ebit_ltm_history_2",
    "past_ebit_ltm_history_3",
    "past_ebit_ltm_history_4",
    "past_ebit_ltm_history_5",
    "past_ebit_3y_avg",
    "past_ebit_5y_avg",
    "past_ebit_single_growth_1y",
    "past_ebit_single_growth_3y",
    "past_ebit_single_growth_5y",
    "past_ebit_margin_1y",
    "past_ebit_margin",
    "past_ebitda",
    "past_ebitda_margin",
    "past_gross_profit_margin",
    "past_last_filing_date",
    "past_net_income_single_growth_3y",
    "past_net_income_single_growth_5y",
    "past_earnings_per_share_single_growth_3y",
    "past_earnings_per_share_single_growth_5y",
    "past_gross_profit_margin_1y",
    "past_net_income_margin",
    "past_net_income_margin_1y",
    "past_change_in_unearned_revenue",
    "past_unearned_revenue_percent_of_sales",
    "past_ebt_including",
    "past_unusual_items",
    "past_unusual_item_ratio",
    "past_operating_revenue_percent",
    "past_years_profitable",
    "past_trading_since_years",
    "past_non_operating_revenue",
    "past_non_operating_revenue_ratio",
    "past_non_operating_revenue_ratio_1y",
    "past_non_operating_revenue_ratio_delta",
    "past_income_tax_to_ebit_ratio",
    "past_capital_employed_ltm_history_0",
    "past_capital_employed_ltm_history_1",
    "past_capital_employed_ltm_history_2",
    "past_capital_employed_ltm_history_3",
    "past_capital_employed_ltm_history_4",
    "past_capital_employed_ltm_history_5",
    "past_return_on_capital_employed_ltm_history_0",
    "past_return_on_capital_employed_ltm_history_1",
    "past_return_on_capital_employed_ltm_history_2",
    "past_return_on_capital_employed_ltm_history_3",
    "past_return_on_capital_employed_ltm_history_4",
    "past_return_on_capital_employed_ltm_history_5",
    "past_latest_fiscal_year",
    "past_latest_fiscal_quarter",
    "past_business_revenue_segments_banking",
    "past_selling_general_admin_expense",
    "past_research_development_expense",
    "past_sales_marketing_expense",
    "past_stock_based_compensation",
    "past_depreciation_amortization",
    "past_general_admin_expense",
    "past_non_operating_expense",
    "past_last_processed_filing_date",
    "past_last_company_filing_date",
    "past_last_announced_date",
    "value_pe",
    "value_pb",
    "value_peg",
    "value_beta_5y",
    "value_beta_5y_unlevered",
    "value_intrinsic_discount",
    "value_npv_per_share",
    "value_earnings_per_share_growth_1y",
    "value_intrinsic_value_de",
    "value_intrinsic_value_iso",
    "value_intrinsic_value_npv",
    "value_intrinsic_value_pvtv",
    "value_intrinsic_value_model",
    "value_intrinsic_value_pv_5y",
    "value_intrinsic_value_tax_rate",
    "value_intrinsic_value_levered_beta",
    "value_intrinsic_value_adr_per_share",
    "value_intrinsic_value_npv_per_share",
    "value_intrinsic_value_two_stage_fcf_scale",
    "value_intrinsic_value_two_stage_fcf_fcf_ltm",
    "value_intrinsic_value_two_stage_fcf_first_stage_2026_data",
    "value_intrinsic_value_two_stage_fcf_first_stage_2026_source",
    "value_intrinsic_value_two_stage_fcf_first_stage_2026_discounted",
    "value_intrinsic_value_two_stage_fcf_first_stage_2027_data",
    "value_intrinsic_value_two_stage_fcf_first_stage_2027_source",
    "value_intrinsic_value_two_stage_fcf_first_stage_2027_discounted",
    "value_intrinsic_value_two_stage_fcf_first_stage_2028_data",
    "value_intrinsic_value_two_stage_fcf_first_stage_2028_source",
    "value_intrinsic_value_two_stage_fcf_first_stage_2028_discounted",
    "value_intrinsic_value_two_stage_fcf_first_stage_2029_data",
    "value_intrinsic_value_two_stage_fcf_first_stage_2029_source",
    "value_intrinsic_value_two_stage_fcf_first_stage_2029_discounted",
    "value_intrinsic_value_two_stage_fcf_first_stage_2030_data",
    "value_intrinsic_value_two_stage_fcf_first_stage_2030_source",
    "value_intrinsic_value_two_stage_fcf_first_stage_2030_discounted",
    "value_intrinsic_value_two_stage_fcf_first_stage_2031_data",
    "value_intrinsic_value_two_stage_fcf_first_stage_2031_source",
    "value_intrinsic_value_two_stage_fcf_first_stage_2031_discounted",
    "value_intrinsic_value_two_stage_fcf_first_stage_2032_data",
    "value_intrinsic_value_two_stage_fcf_first_stage_2032_source",
    "value_intrinsic_value_two_stage_fcf_first_stage_2032_discounted",
    "value_intrinsic_value_two_stage_fcf_first_stage_2033_data",
    "value_intrinsic_value_two_stage_fcf_first_stage_2033_source",
    "value_intrinsic_value_two_stage_fcf_first_stage_2033_discounted",
    "value_intrinsic_value_two_stage_fcf_first_stage_2034_data",
    "value_intrinsic_value_two_stage_fcf_first_stage_2034_source",
    "value_intrinsic_value_two_stage_fcf_first_stage_2034_discounted",
    "value_intrinsic_value_two_stage_fcf_first_stage_2035_data",
    "value_intrinsic_value_two_stage_fcf_first_stage_2035_source",
    "value_intrinsic_value_two_stage_fcf_first_stage_2035_discounted",
    "value_intrinsic_value_two_stage_fcf_scale_numeric",
    "value_intrinsic_value_two_stage_fcf_growth_cagr_5y",
    "value_intrinsic_value_two_stage_fcf_shares_outstanding",
    "value_intrinsic_value_two_stage_fcf_capital_to_revenue_ratio_3yr_avg",
    "value_intrinsic_value_cost_of_equity",
    "value_intrinsic_value_equity_premium",
    "value_intrinsic_value_excess_returns_book_value",
    "value_intrinsic_value_excess_returns_stable_eps",
    "value_intrinsic_value_excess_returns_equity_cost",
    "value_intrinsic_value_excess_returns_excess_return",
    "value_intrinsic_value_excess_returns_stable_book_value",
    "value_intrinsic_value_excess_returns_stable_eps_source",
    "value_intrinsic_value_excess_returns_return_on_equity_avg",
    "value_intrinsic_value_excess_returns_stable_book_value_source",
    "value_intrinsic_value_risk_free_rate",
    "value_intrinsic_value_terminal_value",
    "value_intrinsic_value_unlevered_beta",
    "value_intrinsic_value_dividend_discount_dps",
    "value_intrinsic_value_dividend_discount_roe",
    "value_intrinsic_value_dividend_discount_payout",
    "value_intrinsic_value_dividend_discount_ddm_growth",
    "value_intrinsic_value_dividend_discount_ddm_source",
    "value_intrinsic_value_dividend_discount_npv_per_share",
    "value_intrinsic_value_dividend_discount_expected_growth",
    "value_intrinsic_value_intrinsic_discount",
    "value_intrinsic_value_levered_beta_actual",
    "value_market_cap_usd",
    "value_market_cap",
    "value_market_cap_band",
    "value_last_share_price",
    "value_price_to_sales",
    "value_ev_to_sales",
    "value_ev_to_ebitda",
    "value_return_1d",
    "value_return_7d",
    "value_return_30d",
    "value_return_90d",
    "value_return_ytd",
    "value_return_1yr_abs",
    "value_return_3yr_abs",
    "value_return_5yr_abs",
    "value_return_7d_total_return",
    "value_return_30d_total_return",
    "value_return_90d_total_return",
    "value_return_ytd_total_return",
    "value_return_1yr_total_return",
    "value_return_3yr_total_return",
    "value_return_5yr_total_return",
    "value_return_since_ipo_abs",
    "value_price_target",
    "value_price_target_low",
    "value_price_target_high",
    "value_price_target_analyst_count",
    "value_market_cap_movement_1d",
    "value_market_cap_movement_usd_1d",
    "value_market_cap_movement_7d",
    "value_market_cap_movement_usd_7d",
    "value_market_cap_movement_30d",
    "value_market_cap_movement_usd_30d",
    "value_market_cap_movement_90d",
    "value_market_cap_movement_usd_90d",
    "value_market_cap_movement_1y",
    "value_market_cap_movement_usd_1y",
    "value_market_cap_movement_3y",
    "value_market_cap_movement_usd_3y",
    "value_market_cap_movement_5y",
    "value_market_cap_movement_usd_5y",
    "extended_data_scores_value",
    "extended_data_scores_income",
    "extended_data_scores_health",
    "extended_data_scores_past",
    "extended_data_scores_future",
    "extended_data_scores_management",
    "extended_data_scores_misc",
    "extended_data_scores_total",
    "extended_data_scores_sentence",
    "extended_data_industry_averages_industry_id",
    "extended_data_industry_averages_country_iso",
    "extended_data_industry_averages_name",
    "extended_data_industry_averages_value_score",
    "extended_data_industry_averages_dividends_score",
    "extended_data_industry_averages_future_performance_score",
    "extended_data_industry_averages_health_score",
    "extended_data_industry_averages_past_performance_score",
    "extended_data_industry_averages_total_score",
    "extended_data_industry_averages_share_price",
    "extended_data_industry_averages_market_cap",
    "extended_data_industry_averages_intrinsic_discount",
    "extended_data_industry_averages_analyst_count",
    "extended_data_industry_averages_pe",
    "extended_data_industry_averages_pb",
    "extended_data_industry_averages_peg",
    "extended_data_industry_averages_future_one_year_growth",
    "extended_data_industry_averages_future_three_year_growth",
    "extended_data_industry_averages_past_one_year_growth",
    "extended_data_industry_averages_past_five_year_growth",
    "extended_data_industry_averages_roe",
    "extended_data_industry_averages_roa",
    "extended_data_industry_averages_dividend_yield",
    "extended_data_industry_averages_future_dividend_yield",
    "extended_data_industry_averages_eps",
    "extended_data_industry_averages_insider_buying",
    "extended_data_industry_averages_debt_equity",
    "extended_data_industry_averages_levered_beta",
    "extended_data_industry_averages_unlevered_beta",
    "extended_data_industry_averages_total_base_count",
    "extended_data_industry_averages_profitable_count",
    "extended_data_industry_averages_analyst_coverage_count",
    "extended_data_industry_averages_dividend_count",
    "extended_data_industry_averages_beta_count",
    "extended_data_industry_averages_earnings_per_share_growth_annual",
    "extended_data_industry_averages_net_income_growth_annual",
    "extended_data_industry_averages_cash_ops_growth_annual",
    "extended_data_industry_averages_revenue_growth_annual",
    "extended_data_industry_averages_levered_beta_median",
    "extended_data_industry_averages_base_source",
    "extended_data_industry_averages_profitable_source",
    "extended_data_industry_averages_analyst_source",
    "extended_data_industry_averages_dividend_source",
    "extended_data_industry_averages_beta_source",
    "extended_data_industry_averages_all_value_score",
    "extended_data_industry_averages_all_dividends_score",
    "extended_data_industry_averages_all_future_performance_score",
    "extended_data_industry_averages_all_health_score",
    "extended_data_industry_averages_all_past_performance_score",
    "extended_data_industry_averages_all_total_score",
    "extended_data_industry_averages_all_share_price",
    "extended_data_industry_averages_all_market_cap",
    "extended_data_industry_averages_all_intrinsic_discount",
    "extended_data_industry_averages_all_analyst_count",
    "extended_data_industry_averages_all_pe",
    "extended_data_industry_averages_all_pb",
    "extended_data_industry_averages_all_peg",
    "extended_data_industry_averages_all_future_one_year_growth",
    "extended_data_industry_averages_all_future_three_year_growth",
    "extended_data_industry_averages_all_past_one_year_growth",
    "extended_data_industry_averages_all_past_five_year_growth",
    "extended_data_industry_averages_all_roe",
    "extended_data_industry_averages_all_roa",
    "extended_data_industry_averages_all_dividend_yield",
    "extended_data_industry_averages_all_future_dividend_yield",
    "extended_data_industry_averages_all_eps",
    "extended_data_industry_averages_all_insider_buying",
    "extended_data_industry_averages_all_debt_equity",
    "extended_data_industry_averages_all_levered_beta",
    "extended_data_industry_averages_all_unlevered_beta",
    "extended_data_industry_averages_all_total_base_count",
    "extended_data_industry_averages_all_profitable_count",
    "extended_data_industry_averages_all_analyst_coverage_count",
    "extended_data_industry_averages_all_dividend_count",
    "extended_data_industry_averages_all_beta_count",
    "extended_data_industry_averages_all_earnings_per_share_growth_annual",
    "extended_data_industry_averages_all_net_income_growth_annual",
    "extended_data_industry_averages_all_cash_ops_growth_annual",
    "extended_data_industry_averages_all_revenue_growth_annual",
    "extended_data_industry_averages_all_levered_beta_median",
    "health_industry_analysis",
    "past_industry_analysis_revenue_segments_transportation_trucking",
    "past_business_revenue_segments_transportation_trucking",
    "past_geographic_revenue_segments_people_s_republic_of_china",
    "value_intrinsic_value_excess_returns",
    "value_intrinsic_value_npv_per_share_reported_currency",
    "extended_data_statements_dividend_growth_statement_description",
    "extended_data_statements_dividend_growth_statement_data_last_payment",
    "extended_data_statements_dividend_growth_statement_data_first_payment",
    "extended_data_statements_dividend_growth_statement_data_min_threshold",
    "extended_data_statements_dividend_growth_statement_data_dividend_yield",
    "extended_data_statements_dividend_growth_statement_data_dividend_paying_years",
    "extended_data_statements_dividend_growth_statement_type",
    "extended_data_statements_dividend_payout_statement_data_threshold",
    "extended_data_statements_dividend_payout_statement_data_payout_ratio",
    "extended_data_statements_dividend_payout_statement_data_min_threshold",
    "extended_data_statements_dividend_payout_statement_data_dividend_yield",
    "extended_data_statements_dividend_payout_statement_data_payout_ratio_inverse",
    "extended_data_statements_dividend_payout_statement_type",
    "extended_data_statements_dividend_payout_statement3y_description",
    "extended_data_statements_dividend_payout_statement3y_data_threshold",
    "extended_data_statements_dividend_payout_statement3y_data_min_threshold",
    "extended_data_statements_dividend_payout_statement3y_data_payout_ratio_3y",
    "extended_data_statements_dividend_payout_statement3y_data_dividend_yield_future",
    "extended_data_statements_dividend_payout_statement3y_data_payout_ratio_3y_inverse",
    "extended_data_statements_dividend_payout_statement3y_type",
    "extended_data_statements_dividend_volatility_statement_description",
    "extended_data_statements_dividend_volatility_statement_data_min_threshold",
    "extended_data_statements_dividend_volatility_statement_data_dividend_yield",
    "extended_data_statements_dividend_volatility_statement_data_dividend_paying_years",
    "extended_data_statements_dividend_volatility_statement_type",
    "extended_data_statements_dividend_yield_low_risk_statement_date_generated",
    "extended_data_statements_dividend_yield_low_risk_statement_description",
    "extended_data_statements_dividend_yield_low_risk_statement_data_low_risk_rate",
    "extended_data_statements_dividend_yield_low_risk_statement_data_dividend_yield",
    "extended_data_statements_dividend_yield_low_risk_statement_type",
    "extended_data_statements_dividend_yield_market_top_statement_description",
    "extended_data_statements_dividend_yield_market_top_statement_type",
    "extended_data_statements_future_cash2y_statement_description",
    "extended_data_statements_future_cash2y_statement_data_cash_ops_2y",
    "extended_data_statements_future_cash2y_statement_data_cash_ops_now",
    "extended_data_statements_future_cash2y_statement_data_cash_ops_growth_2y",
    "extended_data_statements_future_cash2y_statement_type",
    "extended_data_statements_future_earnings_high_growth_description",
    "extended_data_statements_future_earnings_high_growth_data_net_income_now",
    "extended_data_statements_future_earnings_high_growth_data_minimum_threshold",
    "extended_data_statements_future_earnings_high_growth_data_maximum_net_income",
    "extended_data_statements_future_earnings_high_growth_data_net_income_growth_annual",
    "extended_data_statements_future_earnings_high_growth_type",
    "extended_data_statements_future_earnings_vs_market_average_description",
    "extended_data_statements_future_earnings_vs_market_average_data_market_average",
    "extended_data_statements_future_earnings_vs_market_average_data_maximum_net_income",
    "extended_data_statements_future_earnings_vs_market_average_data_net_income_growth_annual",
    "extended_data_statements_future_earnings_vs_market_average_data_net_income_growth_market",
    "extended_data_statements_future_earnings_vs_market_average_type",
    "extended_data_statements_future_earnings_vs_risk_free_rate_description",
    "extended_data_statements_future_earnings_vs_risk_free_rate_data_net_income_now",
    "extended_data_statements_future_earnings_vs_risk_free_rate_data_minimum_threshold",
    "extended_data_statements_future_earnings_vs_risk_free_rate_data_maximum_net_income",
    "extended_data_statements_future_earnings_vs_risk_free_rate_data_net_income_growth_annual",
    "extended_data_statements_future_earnings_vs_risk_free_rate_type",
    "extended_data_statements_future_growth1y_statement_description",
    "extended_data_statements_future_growth1y_statement_data_minimum_threshold",
    "extended_data_statements_future_growth1y_statement_data_earnings_per_share_1y",
    "extended_data_statements_future_growth1y_statement_data_earnings_per_share_now",
    "extended_data_statements_future_growth1y_statement_data_earnings_per_share_growth_1y",
    "extended_data_statements_future_growth1y_statement_type",
    "extended_data_statements_future_growth3y_statement_description",
    "extended_data_statements_future_growth3y_statement_data_minimum_threshold",
    "extended_data_statements_future_growth3y_statement_data_earnings_per_share_3y",
    "extended_data_statements_future_growth3y_statement_data_earnings_per_share_now",
    "extended_data_statements_future_growth3y_statement_data_earnings_per_share_growth_3y",
    "extended_data_statements_future_growth3y_statement_type",
    "extended_data_statements_future_meaningless_future_statement_data_revenue_1y",
    "extended_data_statements_future_meaningless_future_statement_data_revenue_2y",
    "extended_data_statements_future_meaningless_future_statement_data_revenue_3y",
    "extended_data_statements_future_meaningless_future_statement_data_net_income_1y",
    "extended_data_statements_future_meaningless_future_statement_data_net_income_2y",
    "extended_data_statements_future_meaningless_future_statement_data_net_income_3y",
    "extended_data_statements_future_meaningless_future_statement_data_return_on_equity_3y",
    "extended_data_statements_future_meaningless_future_statement_data_earnings_per_share_1y",
    "extended_data_statements_future_meaningless_future_statement_data_earnings_per_share_2y",
    "extended_data_statements_future_meaningless_future_statement_data_earnings_per_share_3y",
    "extended_data_statements_future_meaningless_future_statement_data_net_income_growth_annual",
    "extended_data_statements_future_net_income2y_statement_description",
    "extended_data_statements_future_net_income2y_statement_data_net_income_2y",
    "extended_data_statements_future_net_income2y_statement_data_net_income_now",
    "extended_data_statements_future_net_income2y_statement_data_net_income_growth_2y",
    "extended_data_statements_future_net_income2y_statement_type",
    "extended_data_statements_future_projected_roebench_statement_description",
    "extended_data_statements_future_projected_roebench_statement_data_return_on_equity",
    "extended_data_statements_future_projected_roebench_statement_type",
    "extended_data_statements_future_projected_roeindustry_statement_description",
    "extended_data_statements_future_projected_roeindustry_statement_data_industry_name",
    "extended_data_statements_future_projected_roeindustry_statement_data_return_on_equity_3y",
    "extended_data_statements_future_projected_roeindustry_statement_data_return_on_equity_industry",
    "extended_data_statements_future_projected_roeindustry_statement_type",
    "extended_data_statements_future_projected_roestatement_description",
    "extended_data_statements_future_projected_roestatement_data_return_on_equity",
    "extended_data_statements_future_projected_roestatement_data_return_on_equity_3y",
    "extended_data_statements_future_projected_roestatement_type",
    "extended_data_statements_future_revenue2y_statement_description",
    "extended_data_statements_future_revenue2y_statement_data_revenue_2y",
    "extended_data_statements_future_revenue2y_statement_data_renenue_now",
    "extended_data_statements_future_revenue2y_statement_data_revenue_growth_2y",
    "extended_data_statements_future_revenue2y_statement_type",
    "extended_data_statements_future_revenue_high_growth_description",
    "extended_data_statements_future_revenue_high_growth_data_minimum_threshold",
    "extended_data_statements_future_revenue_high_growth_data_maximum_net_income",
    "extended_data_statements_future_revenue_high_growth_data_revenue_growth_annual",
    "extended_data_statements_future_revenue_high_growth_type",
    "extended_data_statements_future_revenue_vs_market_average_description",
    "extended_data_statements_future_revenue_vs_market_average_data_maximum_revenue",
    "extended_data_statements_future_revenue_vs_market_average_data_revenue_growth_annual",
    "extended_data_statements_future_revenue_vs_market_average_data_revenue_growth_market",
    "extended_data_statements_future_revenue_vs_market_average_type",
    "extended_data_statements_health_assets_to_liabs_statement_date_generated",
    "extended_data_statements_health_assets_to_liabs_statement_description",
    "extended_data_statements_health_assets_to_liabs_statement_data_current_solvency_ratio",
    "extended_data_statements_health_assets_to_liabs_statement_type",
    "extended_data_statements_health_cash_burn_growth_statement_date_generated",
    "extended_data_statements_health_cash_burn_growth_statement_description",
    "extended_data_statements_health_cash_burn_growth_statement_data_net_income",
    "extended_data_statements_health_cash_burn_growth_statement_data_net_income_5y_avg",
    "extended_data_statements_health_cash_burn_growth_statement_data_levered_free_cash_flow",
    "extended_data_statements_health_cash_burn_growth_statement_data_levered_free_cash_flow_growth_years",
    "extended_data_statements_health_cash_burn_growth_statement_data_levered_free_cash_flow_growth_annual",
    "extended_data_statements_health_cash_burn_growth_statement_type",
    "extended_data_statements_health_cash_burn_stable_statement_date_generated",
    "extended_data_statements_health_cash_burn_stable_statement_description",
    "extended_data_statements_health_cash_burn_stable_statement_data_net_income",
    "extended_data_statements_health_cash_burn_stable_statement_data_net_income_5y_avg",
    "extended_data_statements_health_cash_burn_stable_statement_data_levered_free_cash_flow",
    "extended_data_statements_health_cash_burn_stable_statement_data_levered_free_cash_flow_stable_years",
    "extended_data_statements_health_cash_burn_stable_statement_type",
    "extended_data_statements_health_cash_debt_statement_date_generated",
    "extended_data_statements_health_cash_debt_statement_description",
    "extended_data_statements_health_cash_debt_statement_data_net_income",
    "extended_data_statements_health_cash_debt_statement_data_total_debt",
    "extended_data_statements_health_cash_debt_statement_data_net_income_5y_avg",
    "extended_data_statements_health_cash_debt_statement_data_levered_free_cash_flow",
    "extended_data_statements_health_cash_debt_statement_data_operating_cash_flow_to_total_debt",
    "extended_data_statements_health_cash_debt_statement_type",
    "extended_data_statements_health_current_assets_to_debt_statement_date_generated",
    "extended_data_statements_health_current_assets_to_debt_statement_description",
    "extended_data_statements_health_current_assets_to_debt_statement_data_total_debt",
    "extended_data_statements_health_current_assets_to_debt_statement_data_total_equity",
    "extended_data_statements_health_current_assets_to_debt_statement_data_current_assets_to_total_debt",
    "extended_data_statements_health_current_assets_to_debt_statement_type",
    "extended_data_statements_health_current_assets_to_ltliabs_statement_date_generated",
    "extended_data_statements_health_current_assets_to_ltliabs_statement_description",
    "extended_data_statements_health_current_assets_to_ltliabs_statement_data_long_term_liab",
    "extended_data_statements_health_current_assets_to_ltliabs_statement_data_current_assets_to_long_term_liab",
    "extended_data_statements_health_current_assets_to_ltliabs_statement_type",
    "extended_data_statements_health_debt_growth_statement_date_generated",
    "extended_data_statements_health_debt_growth_statement_description",
    "extended_data_statements_health_debt_growth_statement_data_total_debt",
    "extended_data_statements_health_debt_growth_statement_data_total_equity",
    "extended_data_statements_health_debt_growth_statement_data_total_debt_max",
    "extended_data_statements_health_debt_growth_statement_data_debt_to_equity_ratio",
    "extended_data_statements_health_debt_growth_statement_data_debt_to_equity_ratio_past",
    "extended_data_statements_health_debt_growth_statement_type",
    "extended_data_statements_health_debt_interest_statement_date_generated",
    "extended_data_statements_health_debt_interest_statement_is_score",
    "extended_data_statements_health_debt_interest_statement_description",
    "extended_data_statements_health_debt_interest_statement_data_net_income",
    "extended_data_statements_health_debt_interest_statement_data_total_debt",
    "extended_data_statements_health_debt_interest_statement_data_net_income_5y_avg",
    "extended_data_statements_health_debt_interest_statement_data_earnings_per_share",
    "extended_data_statements_health_debt_interest_statement_data_net_interest_cover",
    "extended_data_statements_health_debt_interest_statement_data_levered_free_cash_flow",
    "extended_data_statements_health_debt_interest_statement_type",
    "extended_data_statements_health_debt_statement_date_generated",
    "extended_data_statements_health_debt_statement_description",
    "extended_data_statements_health_debt_statement_data_total_debt",
    "extended_data_statements_health_debt_statement_data_total_equity",
    "extended_data_statements_health_debt_statement_data_debt_to_equity_ratio",
    "extended_data_statements_health_debt_statement_type",
    "extended_data_statements_health_inventory_statement_date_generated",
    "extended_data_statements_health_inventory_statement_description",
    "extended_data_statements_health_inventory_statement_data_fixed_to_total_assets",
    "extended_data_statements_health_inventory_statement_type",
    "extended_data_statements_management_board_tenure_statement_description",
    "extended_data_statements_management_board_tenure_statement_data_board_tenure",
    "extended_data_statements_management_board_tenure_statement_type",
    "extended_data_statements_management_ceoover_compensation_statement_description",
    "extended_data_statements_management_ceoover_compensation_statement_data_market",
    "extended_data_statements_management_ceoover_compensation_statement_data_ceo_name",
    "extended_data_statements_management_ceoover_compensation_statement_data_median_compensation_usd",
    "extended_data_statements_management_ceoover_compensation_statement_data_ceo_compensation_total_usd",
    "extended_data_statements_management_ceoover_compensation_statement_type",
    "extended_data_statements_management_ceosalary_growth_statement_description",
    "extended_data_statements_management_ceosalary_growth_statement_data_ceo_name",
    "extended_data_statements_management_ceosalary_growth_statement_data_earnings_per_share",
    "extended_data_statements_management_ceosalary_growth_statement_data_ceo_salary_growth_1y",
    "extended_data_statements_management_ceosalary_growth_statement_data_earnings_per_share_1y",
    "extended_data_statements_management_ceosalary_growth_statement_data_earnings_per_share_growth_1y",
    "extended_data_statements_management_ceosalary_growth_statement_type",
    "extended_data_statements_management_insider_trade_statement_description",
    "extended_data_statements_management_insider_trade_statement_data_buying_3_month",
    "extended_data_statements_management_insider_trade_statement_data_total_ex_3_month",
    "extended_data_statements_management_insider_trade_statement_data_buying_3_month_value",
    "extended_data_statements_management_insider_trade_statement_data_insider_buying_ratio",
    "extended_data_statements_management_insider_trade_statement_data_selling_3_month_value",
    "extended_data_statements_management_insider_trade_statement_type",
    "extended_data_statements_management_pro_tenure_statement_description",
    "extended_data_statements_management_pro_tenure_statement_data_management_tenure",
    "extended_data_statements_management_pro_tenure_statement_type",
    "extended_data_statements_misc_analyst_coverage_statement_date_generated",
    "extended_data_statements_misc_analyst_coverage_statement_description",
    "extended_data_statements_misc_analyst_coverage_statement_data_analyst_count",
    "extended_data_statements_misc_analyst_coverage_statement_type",
    "extended_data_statements_misc_exchange_traded_fund_statement_date_generated",
    "extended_data_statements_misc_exchange_traded_fund_statement_type",
    "extended_data_statements_misc_market_cap_statement_date_generated",
    "extended_data_statements_misc_market_cap_statement_data_market_cap_usd",
    "extended_data_statements_misc_market_cap_statement_type",
    "extended_data_statements_misc_out_dated_data_statement_date_generated",
    "extended_data_statements_misc_out_dated_data_statement_data_days_since_last_update",
    "extended_data_statements_misc_out_dated_data_statement_type",
    "extended_data_statements_misc_price_volatility_statement_date_generated",
    "extended_data_statements_misc_price_volatility_statement_description",
    "extended_data_statements_misc_price_volatility_statement_type",
    "extended_data_statements_misc_trading_halt_statement_date_generated",
    "extended_data_statements_misc_trading_halt_statement_type",
    "extended_data_statements_misc_trading_halt_statement_latex_formula",
    "extended_data_statements_past_growth1y5y_statement_date_generated",
    "extended_data_statements_past_growth1y5y_statement_description",
    "extended_data_statements_past_growth1y5y_statement_data_earnings",
    "extended_data_statements_past_growth1y5y_statement_data_earnings_1y",
    "extended_data_statements_past_growth1y5y_statement_data_earnings_growth_1y",
    "extended_data_statements_past_growth1y5y_statement_data_earnings_growth_5y",
    "extended_data_statements_past_growth1y5y_statement_data_trading_since_years",
    "extended_data_statements_past_growth1y5y_statement_type",
    "extended_data_statements_past_growth5y_statement_date_generated",
    "extended_data_statements_past_growth5y_statement_description",
    "extended_data_statements_past_growth5y_statement_data_earnings",
    "extended_data_statements_past_growth5y_statement_data_earnings_5y_avg",
    "extended_data_statements_past_growth5y_statement_data_earnings_growth_5y",
    "extended_data_statements_past_growth5y_statement_data_trading_since_years",
    "extended_data_statements_past_growth5y_statement_type",
    "extended_data_statements_past_meaningless_past_statement_date_generated",
    "extended_data_statements_past_meaningless_past_statement_is_score",
    "extended_data_statements_past_meaningless_past_statement_description",
    "extended_data_statements_past_meaningless_past_statement_data_revenue",
    "extended_data_statements_past_meaningless_past_statement_data_net_income",
    "extended_data_statements_past_meaningless_past_statement_data_return_on_assets",
    "extended_data_statements_past_meaningless_past_statement_data_return_on_equity",
    "extended_data_statements_past_meaningless_past_statement_data_return_on_capital_employed",
    "extended_data_statements_past_meaningless_past_statement_data_return_on_capital_employed_past",
    "extended_data_statements_past_roastatement_date_generated",
    "extended_data_statements_past_roastatement_description",
    "extended_data_statements_past_roastatement_data_return_on_assets",
    "extended_data_statements_past_roastatement_data_return_on_assets_industry",
    "extended_data_statements_past_roastatement_type",
    "extended_data_statements_past_rocestatement_date_generated",
    "extended_data_statements_past_rocestatement_description",
    "extended_data_statements_past_rocestatement_data_net_income",
    "extended_data_statements_past_rocestatement_data_total_assets",
    "extended_data_statements_past_rocestatement_data_current_liabilities",
    "extended_data_statements_past_rocestatement_data_return_on_capital_growth",
    "extended_data_statements_past_rocestatement_data_return_on_capital_employed",
    "extended_data_statements_past_rocestatement_data_return_on_capital_employed_past",
    "extended_data_statements_past_rocestatement_type",
    "extended_data_statements_past_roestatement_date_generated",
    "extended_data_statements_past_roestatement_description",
    "extended_data_statements_past_roestatement_data_total_equity",
    "extended_data_statements_past_roestatement_data_return_on_equity",
    "extended_data_statements_past_roestatement_data_total_debt_equity",
    "extended_data_statements_past_roestatement_data_earnings_continued_ops",
    "extended_data_statements_past_roestatement_type",
    "extended_data_statements_past_vs_market_growth_statement_date_generated",
    "extended_data_statements_past_vs_market_growth_statement_description",
    "extended_data_statements_past_vs_market_growth_statement_data_earnings",
    "extended_data_statements_past_vs_market_growth_statement_data_earnings_1y",
    "extended_data_statements_past_vs_market_growth_statement_data_earnings_growth_1y",
    "extended_data_statements_past_vs_market_growth_statement_data_eps_growth_industry",
    "extended_data_statements_past_vs_market_growth_statement_type",
    "extended_data_statements_value_intrinsic_statement_date_generated",
    "extended_data_statements_value_intrinsic_statement_description",
    "extended_data_statements_value_intrinsic_statement_data_intrinsic_discount",
    "extended_data_statements_value_intrinsic_statement_type",
    "extended_data_statements_value_intrinsic_uber_statement_date_generated",
    "extended_data_statements_value_intrinsic_uber_statement_description",
    "extended_data_statements_value_intrinsic_uber_statement_data_intrinsic_discount",
    "extended_data_statements_value_intrinsic_uber_statement_type",
    "extended_data_statements_value_meaningless_dcfstatement_date_generated",
    "extended_data_statements_value_meaningless_dcfstatement_data_pb",
    "extended_data_statements_value_meaningless_dcfstatement_data_pe",
    "extended_data_statements_value_meaningless_dcfstatement_data_peg",
    "extended_data_statements_value_meaningless_dcfstatement_data_tertiary_id",
    "extended_data_statements_value_meaningless_dcfstatement_data_intrinsic_discount",
    "extended_data_statements_value_meaningless_dcfstatement_type",
    "extended_data_statements_value_pbvs_industry_statement_date_generated",
    "extended_data_statements_value_pbvs_industry_statement_description",
    "extended_data_statements_value_pbvs_industry_statement_data_pb",
    "extended_data_statements_value_pbvs_industry_statement_data_pb_industry",
    "extended_data_statements_value_pbvs_industry_statement_type",
    "extended_data_statements_value_pegstatement_date_generated",
    "extended_data_statements_value_pegstatement_description",
    "extended_data_statements_value_pegstatement_data_pe",
    "extended_data_statements_value_pegstatement_data_peg",
    "extended_data_statements_value_pegstatement_type",
    "extended_data_statements_value_pevs_industry_statement_date_generated",
    "extended_data_statements_value_pevs_industry_statement_description",
    "extended_data_statements_value_pevs_industry_statement_data_pe",
    "extended_data_statements_value_pevs_industry_statement_data_pe_industry",
    "extended_data_statements_value_pevs_industry_statement_type",
    "extended_data_statements_value_pevs_market_statement_date_generated",
    "extended_data_statements_value_pevs_market_statement_description",
    "extended_data_statements_value_pevs_market_statement_data_pe",
    "extended_data_statements_value_pevs_market_statement_data_pe_market",
    "extended_data_statements_value_pevs_market_statement_type",
    "extended_data_statements_value_return1year_vs_industry_statement_date_generated",
    "extended_data_statements_value_return1year_vs_industry_statement_description",
    "extended_data_statements_value_return1year_vs_industry_statement_data_return_1yr_abs",
    "extended_data_statements_value_return1year_vs_industry_statement_data_flat_return_threshold",
    "extended_data_statements_value_return1year_vs_industry_statement_data_return_1yr_abs_industry",
    "extended_data_statements_value_return1year_vs_industry_statement_type",
    "extended_data_statements_value_return1year_vs_market_statement_date_generated",
    "extended_data_statements_value_return1year_vs_market_statement_description",
    "extended_data_statements_value_return1year_vs_market_statement_data_return_1yr_abs",
    "extended_data_statements_value_return1year_vs_market_statement_data_flat_return_threshold",
    "extended_data_statements_value_return1year_vs_market_statement_data_return_1yr_abs_market",
    "extended_data_statements_value_return1year_vs_market_statement_type",
    "extended_data_statements_value_return30day_vs_industry_statement_date_generated",
    "extended_data_statements_value_return30day_vs_industry_statement_description",
    "extended_data_statements_value_return30day_vs_industry_statement_data_industry",
    "extended_data_statements_value_return30day_vs_industry_statement_data_return_30d",
    "extended_data_statements_value_return30day_vs_industry_statement_data_return_30d_industry",
    "extended_data_statements_value_return30day_vs_industry_statement_type",
    "extended_data_statements_value_return30day_vs_market_statement_date_generated",
    "extended_data_statements_value_return30day_vs_market_statement_description",
    "extended_data_statements_value_return30day_vs_market_statement_data_return_30d",
    "extended_data_statements_value_return30day_vs_market_statement_data_return_30d_market",
    "extended_data_statements_value_return30day_vs_market_statement_type",
    "dividend_upcoming_dividend_date",
    "dividend_upcoming_dividend_amount",
    "dividend_upcoming_dividend_pay_date",
    "dividend_upcoming_dividend_next_date",
    "dividend_upcoming_dividend_currency_id",
    "dividend_upcoming_dividend_record_date",
    "dividend_upcoming_dividend_adjustment_factor",
    "dividend_upcoming_dividend_split_adjusted_amount",
    "past_industry_analysis_revenue_segments_international",
    "past_industry_analysis_revenue_segments_united_states_u_s",
    "past_industry_analysis_revenue_segments_unallocated_contract_manufacturing_human_health",
    "past_business_revenue_segments_international",
    "past_business_revenue_segments_united_states_u_s",
    "past_business_revenue_segments_unallocated_contract_manufacturing_human_health",
    "past_geographic_revenue_segments_chile",
    "past_geographic_revenue_segments_china",
    "past_geographic_revenue_segments_italy",
    "past_geographic_revenue_segments_japan",
    "past_geographic_revenue_segments_spain",
    "past_geographic_revenue_segments_brazil",
    "past_geographic_revenue_segments_canada",
    "past_geographic_revenue_segments_france",
    "past_geographic_revenue_segments_mexico",
    "past_geographic_revenue_segments_germany",
    "past_geographic_revenue_segments_australia",
    "past_geographic_revenue_segments_unallocated",
    "past_geographic_revenue_segments_united_kingdom",
    "past_geographic_revenue_segments_united_states_u_s",
    "past_geographic_revenue_segments_other_emerging_markets",
    "past_geographic_revenue_segments_other_developed_markets",
    "past_industry_analysis_revenue_segments_retail_apparel",
    "past_business_revenue_segments_retail_apparel",
    "past_geographic_revenue_segments_europe",
    "past_geographic_revenue_segments_united_states",
    "extended_data_statements_health_assets_to_equity_statement_date_generated",
    "extended_data_statements_health_assets_to_equity_statement_description",
    "extended_data_statements_health_assets_to_equity_statement_data_assets_equity_ratio",
    "extended_data_statements_health_assets_to_equity_statement_type",
    "extended_data_statements_health_bad_loan_coverage_statement_date_generated",
    "extended_data_statements_health_bad_loan_coverage_statement_description",
    "extended_data_statements_health_bad_loan_coverage_statement_data_allowance_non_perf_loans",
    "extended_data_statements_health_bad_loan_coverage_statement_type",
    "extended_data_statements_health_deposits_to_liabs_statement_date_generated",
    "extended_data_statements_health_deposits_to_liabs_statement_description",
    "extended_data_statements_health_deposits_to_liabs_statement_data_deposits_to_bank_liabilities",
    "extended_data_statements_health_deposits_to_liabs_statement_type",
    "extended_data_statements_health_loans_to_assets_statement_date_generated",
    "extended_data_statements_health_loans_to_assets_statement_description",
    "extended_data_statements_health_loans_to_assets_statement_data_net_loans_to_total_assets",
    "extended_data_statements_health_loans_to_assets_statement_type",
    "extended_data_statements_health_loans_to_deposits_statement_date_generated",
    "extended_data_statements_health_loans_to_deposits_statement_description",
    "extended_data_statements_health_loans_to_deposits_statement_data_total_deposits",
    "extended_data_statements_health_loans_to_deposits_statement_data_net_loans_to_deposits",
    "extended_data_statements_health_loans_to_deposits_statement_type",
    "extended_data_statements_health_non_perf_loan_statement_date_generated",
    "extended_data_statements_health_non_perf_loan_statement_description",
    "extended_data_statements_health_non_perf_loan_statement_data_non_perf_loans_total_loans",
    "extended_data_statements_health_non_perf_loan_statement_type"
]

# UTC timestamp columns to convert → date
utc_cols = [
    "health_last_balance_sheet_update",
    "past_last_earnings_update",
    "past_last_earnings_update_annual",
    "past_last_filing_date",
    "past_last_processed_filing_date",
    "past_last_company_filing_date",
    "past_last_announced_date",
    "extended_data_statements_dividend_yield_low_risk_statement_date_generated",
    "extended_data_statements_health_assets_to_liabs_statement_date_generated",
    "extended_data_statements_health_cash_burn_growth_statement_date_generated",
    "extended_data_statements_health_cash_burn_stable_statement_date_generated",
    "extended_data_statements_health_current_assets_to_ltliabs_statement_date_generated",
    "extended_data_statements_health_debt_interest_statement_date_generated",
    "extended_data_statements_health_debt_statement_date_generated",
    "extended_data_statements_health_inventory_statement_date_generated",
    "extended_data_statements_misc_analyst_coverage_statement_date_generated",
    "extended_data_statements_misc_exchange_traded_fund_statement_date_generated",
    "extended_data_statements_misc_market_cap_statement_date_generated",
    "extended_data_statements_misc_out_dated_data_statement_date_generated",
    "extended_data_statements_misc_price_volatility_statement_date_generated",
    "extended_data_statements_misc_trading_halt_statement_date_generated",
    "extended_data_statements_past_growth1y5y_statement_date_generated",
    "extended_data_statements_past_growth5y_statement_date_generated",
    "extended_data_statements_past_meaningless_past_statement_date_generated",
    "extended_data_statements_past_roastatement_date_generated",
    "extended_data_statements_past_rocestatement_date_generated",
    "extended_data_statements_past_roestatement_date_generated",
    "extended_data_statements_past_vs_market_growth_statement_date_generated",
    "extended_data_statements_value_intrinsic_statement_date_generated",
    "extended_data_statements_value_intrinsic_uber_statement_date_generated",
    "extended_data_statements_value_meaningless_dcfstatement_date_generated",
    "extended_data_statements_value_pbvs_industry_statement_date_generated",
    "extended_data_statements_value_pegstatement_date_generated",
    "extended_data_statements_value_pevs_industry_statement_date_generated",
    "extended_data_statements_value_pevs_market_statement_date_generated",
    "extended_data_statements_value_return1year_vs_industry_statement_date_generated",
    "extended_data_statements_value_return1year_vs_market_statement_date_generated",
    "extended_data_statements_value_return30day_vs_industry_statement_date_generated",
    "extended_data_statements_value_return30day_vs_market_statement_date_generated",
    "dividend_upcoming_dividend_date",
    "dividend_upcoming_dividend_pay_date",
    "dividend_upcoming_dividend_next_date",
    "dividend_upcoming_dividend_record_date",
    "extended_data_statements_health_assets_to_equity_statement_date_generated",
    "extended_data_statements_health_bad_loan_coverage_statement_date_generated",
    "extended_data_statements_health_deposits_to_liabs_statement_date_generated",
    "extended_data_statements_health_loans_to_assets_statement_date_generated",
    "extended_data_statements_health_loans_to_deposits_statement_date_generated",
    "extended_data_statements_health_non_perf_loan_statement_date_generated",
    "extended_data_statements_health_debt_growth_statement_date_generated",
    "extended_data_statements_health_current_assets_to_debt_statement_date_generated",
    "extended_data_statements_health_cash_debt_statement_date_generated",
]

# ================================================================
# HELPER FUNCTIONS
# ================================================================
def flatten_json(obj, prefix=""):
    flat = {}
    if isinstance(obj, dict):
        for k, v in obj.items():
            flat.update(flatten_json(v, f"{prefix}{k}_"))
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            flat.update(flatten_json(v, f"{prefix}{i}_"))
    else:
        flat[prefix[:-1]] = obj
    return flat

def to_snake_case(text):
    text = re.sub(r"[^a-zA-Z0-9]+", "_", text)
    text = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", text)
    return text.lower().strip("_")

def safe_ts(x):
    try:
        if pd.isna(x):
            return None
        if isinstance(x, date):
            return x
        if isinstance(x, datetime):
            return x.date()
        return datetime.fromtimestamp(float(x) / 1000, tz=timezone.utc).date()
    except:
        return None

def parse_html_file(html_file):
    try:
        html = html_file.read_text(encoding="utf-8")
    except Exception:
        return None

    match = re.search(
        r"window\.__REACT_QUERY_STATE__\s*=\s*(\{.*?\})\s*</script>",
        html,
        re.DOTALL | re.MULTILINE,
    )
    if not match:
        return None

    json_text = re.sub(r"\b(undefined|NaN|Infinity)\b", "null", match.group(1))
    try:
        data = json.loads(json_text)
    except Exception:
        return None

    flat = flatten_json(data)

    start_key = "queries_0_state_data_data_id"
    end_key = "queries_0_state_data_data_analysis_data_extended_data_industry_averages_all_leveredBetaMedian"

    if start_key not in flat or end_key not in flat:
        return None

    keys = list(flat.keys())
    start_i = keys.index(start_key)
    end_i = keys.index(end_key)
    slice_keys = keys[start_i:end_i + 1]

    # ============================================================
    # ✅ OVERWRITE date WITH HTML FILE TIMESTAMP
    # ============================================================
    file_creation_ts = pd.to_datetime(
        html_file.stat().st_mtime,
        unit="s",
        utc=True
    ).date()

    record = {"source_file": html_file.stem, "date": file_creation_ts}

    for k in slice_keys:
        clean = (
            k.replace("queries_0_state_data_data_", "")
             .replace("extended_data_analysis_", "")
             .replace("analysis_data_", "")
        )
        record[to_snake_case(clean)] = flat[k]

    return record

# ================================================================
# LOAD & FLATTEN ALL FILES
# ================================================================
html_files = list(html_folder.glob("**/*.html"))
print(f"\n📂 Found {len(html_files)} HTML files")

records = []
for f in tqdm(html_files, desc="Extracting", ncols=100):
    rec = parse_html_file(f)
    if rec:
        records.append(rec)

df = pd.DataFrame(records)

# ================================================================
# CLEAN DATA
# ================================================================
present = [c for c in keep_columns_facts if c in df.columns]
# Insert 'date' as second column
if "date" in df.columns:
    columns_order = [present[0], "date"] + present[1:]
else:
    columns_order = present
df = df[columns_order]

# ================================================================
# CLEAN FLOAT / INVALID VALUES
# ================================================================
for col in df.columns:
    if df.dtypes[col] == object:
        df[col] = df[col].replace(["inf", "-inf", "Infinity", "-Infinity", "NaN"], np.nan)
    df[col] = pd.to_numeric(df[col], errors="ignore")
    df[col] = df[col].replace([np.inf, -np.inf], np.nan)

# ================================================================
# CONVERT 13-DIGIT UTC TIMESTAMPS TO DATE
# ================================================================
for col in utc_cols:
    if col in df.columns:
        df[col] = df[col].apply(lambda x: safe_ts(x) if pd.notna(x) else None)

# ================================================================
# ENSURE DATE FORMAT IS YYYY-MM-DD FOR SQL SERVER
# ================================================================
for col in df.columns:
    if col.endswith("_date") or col.endswith("_date_generated") or col == "date":
        df[col] = pd.to_datetime(df[col], errors='coerce').dt.strftime('%Y-%m-%d')

# ================================================================
# STAGE TO CSV
# ================================================================
df.to_csv("simply_wallstreet_facts.csv", index=False)
print(f"\n✅ Staged {df.shape[0]} rows to simply_wallstreet_facts.csv")
